name: Generate Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source
        uses: actions/checkout@v2 # 引用actions/checkout这个action，与所在的github仓库同名
        with:
          submodules: true
      
      - name: Read .env # 从文件 .env 中读取指定 Hugo 版本
        id: hugo-version
        run: |
          . ./.env
          echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"
        
      # - name: Setup hugo
      #   uses: peaceiris/actions-hugo@v2
      #   with:
      #     hugo-version: "latest" # 默认使用最新 Hugo 版本
      #     extended: true # 设置是否需要 extended 版本
      
      - name: Failed to setup hugo at the "Setup hugo" step #如果最新版本Hugo不可用，则指定可用版本
        # if: ${{ failure() }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ steps.hugo-version.outputs.HUGO_VERSION }}" # 可以修改为.env文件中指定的 Hugo 版本
          extended: true # 设置是否需要 extended 版本
          
      - name: Build
        run: hugo --minify
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # hugo官方提供的action，用于在任务环境中获取hugo
        with:
          deploy_key: ${{ secrets.HUGO_DEPLOY_TOKEN }} # 另外还支持 github_token 和 personal_token
          external_repository: wlchengg/wlchengg.github.io # 修改为你的 GitHub Pages 仓库
          publish_dir: ./public
          keep_files: false
          publish_branch: main
          # 如果使用自定义域名，还需要添加下面一行配置
          # cname: www.fournoas.com
